server:
  port: 8080

spring:
  application:
    name: euem-main-server
  
  datasource:
    url: jdbc:postgresql://localhost:5432/euem_db
    username: euem_user
    password: euem_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mail:
    host: localhost
    port: 587
    username: euem_smtp_user
    password: euem_smtp_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          secret: euem-jwt-secret-key-that-is-at-least-256-bits-long-for-security-purposes

logging:
  level:
    com.euem.server: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

app:
  jwt:
    secret: euem-jwt-secret-key-that-is-at-least-256-bits-long-for-security-purposes
    expiration: 86400000 # 24 hours in milliseconds
  
  otp:
    expiry-minutes: 15
    length: 6
